# Generated by Django 5.2.13 on 2026-09-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_assessment', '0001_initial'),
        ('ami_core', '0002_seed_reference_data'),
        ('ami_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_visitasi', models.DateField()),
                ('waktu_mulai', models.TimeField(blank=True, null=True)),
                ('waktu_selesai', models.TimeField(blank=True, null=True)),
                ('tempat', models.CharField(blank=True, max_length=300, null=True)),
                ('sk_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_tgl', models.DateField(blank=True, null=True)),
                ('sk_file', models.CharField(blank=True, max_length=500, null=True)),
                ('konfirmasi_status', models.CharField(choices=[('belum_konfirmasi', 'Belum Konfirmasi'), ('dikonfirmasi', 'Dikonfirmasi'), ('minta_reschedule', 'Minta Reschedule'), ('ditolak', 'Ditolak')], default='belum_konfirmasi', max_length=20)),
                ('konfirmasi_pada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('dimulai', 'Dimulai'), ('on_progress', 'On Progress'), ('selesai', 'Selesai'), ('closing_done', 'Closing Done'), ('dibatalkan', 'Dibatalkan')], default='terjadwal', max_length=30)),
                ('ba_opening_file', models.CharField(blank=True, max_length=500, null=True)),
                ('ba_closing_file', models.CharField(blank=True, max_length=500, null=True)),
                ('sertifikat_file', models.CharField(blank=True, max_length=500, null=True)),
                ('tgl_closing', models.DateField(blank=True, null=True)),
                ('catatan_closing', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ketua_tim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitasi_ketua_set', to='ami_user.userami')),
                ('notulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitasi_notulis_set', to='ami_user.userami')),
                ('pengisian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitasi_set', to='ami_assessment.pengisian')),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitasi_set', to='ami_core.siklus')),
            ],
            options={
                'verbose_name_plural': 'Visitasi',
                'db_table': 'visitasi',
                'ordering': ['-tgl_visitasi'],
            },
        ),
        migrations.CreateModel(
            name='VisitasiAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.PositiveIntegerField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('judul_sesi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('belum_mulai', 'Belum Mulai'), ('sedang_berlangsung', 'Sedang Berlangsung'), ('selesai', 'Selesai'), ('dilewati', 'Dilewati')], default='belum_mulai', max_length=20)),
                ('notulen_sesi', models.TextField(blank=True, null=True)),
                ('foto_dokumentasi', models.JSONField(blank=True, help_text='Array URL foto', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_pic_set', to='ami_user.userami')),
                ('visitasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_set', to='ami_visitasi.visitasi')),
            ],
            options={
                'verbose_name': 'Agenda Visitasi',
                'verbose_name_plural': 'Agenda Visitasi',
                'db_table': 'visitasi_agenda',
                'ordering': ['visitasi', 'no_urut'],
            },
        ),
        migrations.CreateModel(
            name='VisitasiAnggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ketua_tim', 'Ketua Tim'), ('anggota', 'Anggota'), ('notulis', 'Notulis'), ('pendamping_lp3m', 'Pendamping LP3M')], max_length=20)),
                ('konflik_kepentingan', models.TextField(blank=True, null=True)),
                ('is_hadir', models.BooleanField(default=False)),
                ('waktu_hadir', models.DateTimeField(blank=True, null=True)),
                ('waktu_pulang', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitasi_anggota_set', to='ami_user.userami')),
                ('visitasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_set', to='ami_visitasi.visitasi')),
            ],
            options={
                'verbose_name': 'Anggota Visitasi',
                'verbose_name_plural': 'Anggota Visitasi',
                'db_table': 'visitasi_anggota',
            },
        ),
        migrations.AddConstraint(
            model_name='visitasi',
            constraint=models.UniqueConstraint(fields=('siklus', 'pengisian'), name='uniq_visitasi_siklus_pengisian'),
        ),
        migrations.AddConstraint(
            model_name='visitasianggota',
            constraint=models.UniqueConstraint(fields=('visitasi', 'user'), name='uniq_visitasi_anggota_user'),
        ),
    ]
