# Generated by Django 5.2.13 on 2026-09-07 01:59

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_core', '0002_seed_reference_data'),
        ('ami_master', '0001_initial'),
        ('ami_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengisian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum_mulai', 'Belum Mulai'), ('sedang_diisi', 'Sedang Diisi'), ('submit', 'Submit'), ('validasi_upm', 'Validasi UPM'), ('siap_de', 'Siap DE'), ('completed', 'Completed')], default='belum_mulai', max_length=30)),
                ('total_butir', models.PositiveIntegerField(default=0)),
                ('butir_terisi', models.PositiveIntegerField(default=0)),
                ('skor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('skor_per_standar', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengisian_operator_set', to='ami_user.userami')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengisian_set', to='ami_master.prodi')),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengisian_set', to='ami_core.siklus')),
                ('upm_validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengisian_validator_set', to='ami_user.userami')),
            ],
            options={
                'verbose_name_plural': 'Pengisian',
                'db_table': 'pengisian',
                'ordering': ['-siklus', 'prodi'],
            },
        ),
        migrations.CreateModel(
            name='JawabanButir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kuantitatif', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('nilai_pilihan', models.CharField(blank=True, max_length=200, null=True)),
                ('nilai_narasi', models.TextField(blank=True, null=True)),
                ('nilai_tabel', models.JSONField(blank=True, null=True)),
                ('nilai_auto', models.JSONField(blank=True, null=True)),
                ('rasio_hasil', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('persentase_capaian', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memenuhi_iku', models.BooleanField(blank=True, null=True)),
                ('sumber_data', models.CharField(choices=[('manual', 'Manual'), ('auto_pmb', 'Auto PMB'), ('auto_sikd', 'Auto SIKD'), ('auto_akademik', 'Auto Akademik'), ('import_excel', 'Import Excel')], default='manual', max_length=30)),
                ('catatan_auditee', models.TextField(blank=True, null=True)),
                ('is_terisi', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('diisi_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jawaban_set', to='ami_core.butirpenilaian')),
                ('diisi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawaban_set', to='ami_user.userami')),
                ('pengisian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_set', to='ami_assessment.pengisian')),
            ],
            options={
                'verbose_name_plural': 'Jawaban Butir',
                'db_table': 'jawaban_butir',
            },
        ),
        migrations.CreateModel(
            name='DokumenBukti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=300)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jenis_sumber', models.CharField(choices=[('upload_file', 'Upload File'), ('link_drive', 'Link Drive'), ('link_url', 'Link URL'), ('auto_api', 'Auto API'), ('cross_schema', 'Cross Schema')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='dokumen_bukti/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('link_terverifikasi', models.BooleanField(default=False)),
                ('link_last_checked', models.DateTimeField(blank=True, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('cross_schema_ref', models.JSONField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('belum_diverifikasi', 'Belum Diverifikasi'), ('menunggu_upm', 'Menunggu UPM'), ('terverifikasi', 'Terverifikasi'), ('ditolak', 'Ditolak'), ('perlu_revisi', 'Perlu Revisi')], default='belum_diverifikasi', max_length=30)),
                ('catatan_verifikasi', models.TextField(blank=True, null=True)),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_set', to='ami_core.butirpenilaian')),
                ('diunggah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diunggah_set', to='ami_user.userami')),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diverifikasi_set', to='ami_user.userami')),
                ('jawaban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_set', to='ami_assessment.jawabanbutir')),
                ('pengisian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_set', to='ami_assessment.pengisian')),
            ],
            options={
                'verbose_name_plural': 'Dokumen Bukti',
                'db_table': 'dokumen_bukti',
            },
        ),
        migrations.AddConstraint(
            model_name='pengisian',
            constraint=models.UniqueConstraint(fields=('siklus', 'prodi'), name='uniq_pengisian_siklus_prodi'),
        ),
        migrations.AddIndex(
            model_name='jawabanbutir',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nilai_tabel'], name='idx_jawaban_nilai_tabel_gin'),
        ),
        migrations.AddConstraint(
            model_name='jawabanbutir',
            constraint=models.UniqueConstraint(fields=('pengisian', 'butir'), name='uniq_jawaban_pengisian_butir'),
        ),
    ]
