# Generated by Django 5.2.13 on 2026-09-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_assessment', '0001_initial'),
        ('ami_core', '0014_nonaktifkan_58_butir_lama'),
        ('ami_master', '0006_petakan_status_akreditasi_16_prodi_riil'),
        ('ami_user', '0002_notifikasi'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pengisian',
            name='uniq_pengisian_siklus_prodi',
        ),
        migrations.AddField(
            model_name='pengisian',
            name='cakupan',
            field=models.CharField(choices=[('prodi', 'Program Studi'), ('fakultas', 'UPPS/Fakultas'), ('universitas', 'Universitas')], default='prodi', max_length=15),
        ),
        migrations.AddField(
            model_name='pengisian',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengisian_set', to='ami_master.fakultas'),
        ),
        migrations.AlterField(
            model_name='pengisian',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengisian_set', to='ami_master.prodi'),
        ),
        migrations.AddConstraint(
            model_name='pengisian',
            constraint=models.UniqueConstraint(condition=models.Q(('prodi__isnull', False)), fields=('siklus', 'prodi'), name='uniq_pengisian_siklus_prodi'),
        ),
        migrations.AddConstraint(
            model_name='pengisian',
            constraint=models.UniqueConstraint(condition=models.Q(('fakultas__isnull', False)), fields=('siklus', 'fakultas'), name='uniq_pengisian_siklus_fakultas'),
        ),
        migrations.AddConstraint(
            model_name='pengisian',
            constraint=models.UniqueConstraint(condition=models.Q(('cakupan', 'universitas')), fields=('siklus', 'cakupan'), name='uniq_pengisian_siklus_universitas'),
        ),
    ]
