# Generated by Django 5.2.13 on 2026-09-07 02:31

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_core', '0002_seed_reference_data'),
        ('ami_master', '0001_initial'),
        ('ami_user', '0002_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArsipMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('form_penilaian', 'Form Penilaian'), ('temuan_ptk', 'Temuan PTK'), ('best_practice', 'Best Practice'), ('sk_rektor', 'SK Rektor'), ('notulen_rtm', 'Notulen RTM'), ('sertifikat_ami', 'Sertifikat AMI'), ('berita_acara', 'Berita Acara'), ('laporan_lengkap', 'Laporan Lengkap'), ('lainnya', 'Lainnya')], max_length=50)),
                ('nama_dokumen', models.CharField(max_length=300)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='arsip/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('fulltext_content', models.TextField(blank=True, help_text='Konten hasil ekstraksi untuk fulltext search', null=True)),
                ('fulltext_search', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('synced_to_arsip', models.BooleanField(default=False)),
                ('arsip_universitas_id', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('retensi_sd_tahun', models.PositiveIntegerField(blank=True, null=True)),
                ('is_permanen', models.BooleanField(default=False)),
                ('is_publik', models.BooleanField(default=False)),
                ('akses_role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diunggah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arsip_diunggah_set', to='ami_user.userami')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arsip_set', to='ami_master.prodi')),
                ('siklus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arsip_set', to='ami_core.siklus')),
            ],
            options={
                'verbose_name': 'Arsip',
                'verbose_name_plural': 'Arsip',
                'db_table': 'arsip_metadata',
                'ordering': ['-diunggah_pada'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='idx_arsip_tags_gin'), django.contrib.postgres.indexes.GinIndex(fields=['fulltext_search'], name='idx_arsip_fulltext_gin')],
            },
        ),
    ]
