# Generated by Django 5.2.13 on 2026-09-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_arsip', '0001_initial'),
        ('ami_core', '0015_isi_rubrik_generik_69_butir_baru_skala04'),
        ('ami_user', '0002_notifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsipmetadata',
            name='master_standar',
            field=models.ForeignKey(blank=True, help_text='Standar SN-Dikti terkait dokumen ini, bila relevan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arsip_set', to='ami_core.masterstandar'),
        ),
        migrations.CreateModel(
            name='PencarianArsipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('jumlah_hasil', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicari_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pencarian_arsip_set', to='ami_user.userami')),
                ('siklus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pencarian_arsip_set', to='ami_core.siklus')),
            ],
            options={
                'verbose_name': 'Riwayat Pencarian Arsip',
                'verbose_name_plural': 'Riwayat Pencarian Arsip',
                'db_table': 'arsip_pencarian_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
