# Generated by Django 5.2.13 on 2026-09-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_assessment', '0001_initial'),
        ('ami_core', '0002_seed_reference_data'),
        ('ami_de', '0001_initial'),
        ('ami_user', '0001_initial'),
        ('ami_visitasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fvtb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_fvtb', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rencana_tindakan', models.TextField()),
                ('pic_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('target_capaian', models.TextField(blank=True, null=True)),
                ('estimasi_anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sumber_anggaran', models.CharField(blank=True, max_length=200, null=True)),
                ('progress_persen', models.PositiveSmallIntegerField(default=0)),
                ('update_terakhir', models.TextField(blank=True, null=True)),
                ('update_pada', models.DateTimeField(blank=True, null=True)),
                ('tgl_mulai', models.DateField(blank=True, null=True)),
                ('tenggat_selesai', models.DateField()),
                ('tgl_selesai_aktual', models.DateField(blank=True, null=True)),
                ('sudah_diverifikasi', models.BooleanField(default=False)),
                ('catatan_verifikasi', models.TextField(blank=True, null=True)),
                ('bukti_verifikasi', models.JSONField(blank=True, help_text='Array id DokumenBukti', null=True)),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('standarisasi_dilakukan', models.BooleanField(default=False)),
                ('catatan_standarisasi', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('plan', 'Plan'), ('do', 'Do'), ('check', 'Check'), ('act', 'Act'), ('closed', 'Closed'), ('eskalasi', 'Eskalasi')], default='plan', max_length=20)),
                ('last_notifikasi_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fvtb_pic_set', to='ami_user.userami')),
                ('verifikator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fvtb_verifikator_set', to='ami_user.userami')),
            ],
            options={
                'verbose_name': 'FVTB',
                'verbose_name_plural': 'FVTB',
                'db_table': 'fvtb',
                'ordering': ['-tenggat_selesai'],
            },
        ),
        migrations.CreateModel(
            name='FvtbProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_sebelum', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progress_sesudah', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('update_text', models.TextField()),
                ('bukti_url', models.CharField(blank=True, max_length=500, null=True)),
                ('diupdate_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fvtb_log_set', to='ami_user.userami')),
                ('fvtb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_log_set', to='ami_temuan.fvtb')),
            ],
            options={
                'verbose_name': 'Log Progress FVTB',
                'verbose_name_plural': 'Log Progress FVTB',
                'db_table': 'fvtb_progress_log',
                'ordering': ['-diupdate_pada'],
            },
        ),
        migrations.CreateModel(
            name='Temuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber_temuan', models.CharField(choices=[('de', 'Desk Evaluasi'), ('visitasi', 'Visitasi'), ('manual', 'Manual')], max_length=20)),
                ('klasifikasi', models.CharField(choices=[('KTB', 'Ketidaksesuaian Berat'), ('KTS', 'Ketidaksesuaian Sedang'), ('OB', 'Observasi'), ('BP', 'Best Practice')], max_length=10)),
                ('no_temuan', models.CharField(blank=True, help_text='Auto: "T-S8-001"', max_length=50, null=True)),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi_problem', models.TextField()),
                ('lokasi_temuan', models.CharField(blank=True, max_length=300, null=True)),
                ('standar_dilanggar', models.CharField(blank=True, max_length=500, null=True)),
                ('bukti_referensi', models.TextField(blank=True, null=True)),
                ('dampak', models.TextField(blank=True, null=True)),
                ('urgensi', models.CharField(blank=True, choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('kritis', 'Kritis')], max_length=10, null=True)),
                ('tenggat_tindak_lanjut', models.DateField(blank=True, help_text='KTB: 30 hari, KTS: 60 hari, OB: 90 hari', null=True)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('diidentifikasi', 'Diidentifikasi'), ('rencana_tindak_lanjut', 'Rencana Tindak Lanjut'), ('sedang_tindak_lanjut', 'Sedang Tindak Lanjut'), ('verifikasi', 'Verifikasi'), ('closed', 'Closed'), ('eskalasi', 'Eskalasi')], default='baru', max_length=30)),
                ('layak_replikasi', models.BooleanField(default=False)),
                ('knowledge_base_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temuan_set', to='ami_core.butirpenilaian')),
                ('de_penilaian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temuan_set', to='ami_de.depenilaian')),
                ('dilaporkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temuan_dilaporkan_set', to='ami_user.userami')),
                ('pengisian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temuan_set', to='ami_assessment.pengisian')),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temuan_set', to='ami_core.siklus')),
                ('visitasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temuan_set', to='ami_visitasi.visitasi')),
            ],
            options={
                'verbose_name_plural': 'Temuan',
                'db_table': 'temuan',
                'ordering': ['-siklus', 'klasifikasi'],
            },
        ),
        migrations.AddField(
            model_name='fvtb',
            name='temuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fvtb_set', to='ami_temuan.temuan'),
        ),
        migrations.AddConstraint(
            model_name='fvtb',
            constraint=models.CheckConstraint(condition=models.Q(('progress_persen__gte', 0), ('progress_persen__lte', 100)), name='chk_fvtb_progress_0_100'),
        ),
    ]
