# Generated by Django 5.2.13 on 2026-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_temuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temuan',
            name='klasifikasi',
            field=models.CharField(choices=[('SESUAI', 'Sesuai (Conformity)'), ('OB', 'Observasi (OB)'), ('KTS_MINOR', 'Ketidaksesuaian Minor (KTS Minor)'), ('KTS_MAYOR', 'Ketidaksesuaian Mayor (KTS Mayor)'), ('KTB', 'Ketidaksesuaian Berat (legacy)'), ('KTS', 'Ketidaksesuaian Sedang (legacy)'), ('BP', 'Best Practice (legacy)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='temuan',
            name='tenggat_tindak_lanjut',
            field=models.DateField(blank=True, help_text='KTS Mayor: 1 bulan, KTS Minor: 3 bulan (OB/Sesuai tanpa tenggat PTK)', null=True),
        ),
    ]
