# Generated by Django 5.2.13 on 2026-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_temuan', '0002_alter_temuan_klasifikasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fvtb',
            name='akar_masalah',
            field=models.TextField(blank=True, help_text='Analisis akar masalah (root cause) sebelum menyusun rencana tindakan -- kolom "Akar Masalah" di Form RTL-PTK AMI.', null=True),
        ),
    ]
