# Generated by Django 5.2.13 on 2026-09-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn_nip', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_auditor_de', models.BooleanField(default=False)),
                ('is_auditor_visitasi', models.BooleanField(default=False)),
                ('is_upm', models.BooleanField(default=False)),
                ('is_lp3m', models.BooleanField(default=False)),
                ('is_pimpinan', models.BooleanField(default=False)),
                ('sertifikasi_auditor', models.CharField(blank=True, max_length=100, null=True)),
                ('pengalaman_audit_thn', models.PositiveIntegerField(blank=True, null=True)),
                ('pakta_integritas_signed_at', models.DateTimeField(blank=True, null=True)),
                ('pakta_integritas_file', models.CharField(blank=True, max_length=500, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fakultas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ami_set', to='ami_master.fakultas')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ami_set', to='ami_master.prodi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ami_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AMI',
                'verbose_name_plural': 'User AMI',
                'db_table': 'user_ami',
                'ordering': ['user__username'],
            },
        ),
    ]
