# Generated by Django 5.2.13 on 2026-09-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('isi', models.TextField(blank=True, null=True)),
                ('tipe', models.CharField(blank=True, choices=[('info', 'Info'), ('reminder', 'Reminder'), ('tenggat', 'Tenggat'), ('eskalasi', 'Eskalasi'), ('persetujuan', 'Persetujuan'), ('penugasan_baru', 'Penugasan Baru'), ('sistem', 'Sistem')], max_length=30, null=True)),
                ('ref_entity', models.CharField(blank=True, help_text='"temuan", "fvtb", "penugasan_de", dll', max_length=50, null=True)),
                ('ref_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('ref_url', models.CharField(blank=True, max_length=500, null=True)),
                ('channel_email', models.BooleanField(default=False)),
                ('channel_wa', models.BooleanField(default=False)),
                ('channel_inapp', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_wa', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_set', to='ami_user.userami')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read'], name='idx_notif_user_read')],
            },
        ),
    ]
