# Generated by Django 5.2.13 on 2026-09-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nama_pendek', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('no_urut', models.PositiveSmallIntegerField()),
                ('warna_hex', models.CharField(default='#1B7BB8', max_length=7)),
                ('is_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Standar',
                'db_table': 'standar',
                'ordering': ['no_urut'],
            },
        ),
        migrations.CreateModel(
            name='Tahap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('no_urut', models.PositiveSmallIntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('durasi_hari', models.PositiveIntegerField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tahap',
                'db_table': 'tahap',
                'ordering': ['no_urut'],
            },
        ),
        migrations.CreateModel(
            name='Siklus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_siklus', models.PositiveIntegerField(unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('tahun_akademik', models.CharField(max_length=20)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('sk_rektor_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_rektor_tgl', models.DateField(blank=True, null=True)),
                ('sk_rektor_file', models.CharField(blank=True, max_length=500, null=True)),
                ('konfig', models.JSONField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('closing_notulen_file', models.CharField(blank=True, max_length=500, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Siklus',
                'db_table': 'siklus',
                'ordering': ['-no_siklus'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_siklus_current')],
            },
        ),
        migrations.CreateModel(
            name='ButirPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jenis_input', models.CharField(choices=[('numerik', 'Numerik'), ('rasio', 'Rasio'), ('persentase', 'Persentase'), ('pilihan', 'Pilihan'), ('narasi', 'Narasi'), ('tabel_dinamis', 'Tabel Dinamis'), ('auto_iku', 'Auto IKU')], max_length=30)),
                ('target_iku', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_satuan', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_target', models.CharField(blank=True, choices=[('>=', '>='), ('<=', '<='), ('=', '='), ('>', '>'), ('<', '<')], max_length=5, null=True)),
                ('auto_source_schema', models.CharField(blank=True, max_length=20, null=True)),
                ('auto_source_table', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_query_template', models.TextField(blank=True, null=True)),
                ('bobot', models.PositiveIntegerField(default=1)),
                ('is_wajib', models.BooleanField(default=True)),
                ('is_kuantitatif', models.BooleanField(default=False)),
                ('panduan_pengisian', models.TextField(blank=True, null=True)),
                ('rujukan_dokumen', models.CharField(blank=True, max_length=500, null=True)),
                ('rujukan_sn_dikti', models.CharField(blank=True, max_length=200, null=True)),
                ('no_urut', models.PositiveIntegerField()),
                ('is_aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butir_set', to='ami_core.siklus')),
                ('standar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butir_set', to='ami_core.standar')),
            ],
            options={
                'verbose_name_plural': 'Butir Penilaian',
                'db_table': 'butir_penilaian',
                'ordering': ['siklus', 'standar', 'no_urut'],
                'constraints': [models.UniqueConstraint(fields=('siklus', 'kode'), name='uniq_butir_siklus_kode')],
            },
        ),
    ]
