# Generated by Django 5.2.13 on 2026-09-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_core', '0003_seed_indikator_riil_dari_dok_ami'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulasiAcuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama_lengkap', models.TextField()),
                ('nama_pendek', models.CharField(max_length=100)),
                ('berita_negara', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_tetap', models.DateField(blank=True, null=True)),
                ('tanggal_undang', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('berlaku', 'Berlaku'), ('dicabut', 'Dicabut')], default='berlaku', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mencabut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicabut_oleh_set', to='ami_core.regulasiacuan')),
            ],
            options={
                'verbose_name': 'Regulasi Acuan',
                'verbose_name_plural': 'Regulasi Acuan',
                'db_table': 'regulasi_acuan',
            },
        ),
        migrations.AddField(
            model_name='siklus',
            name='regulasi_acuan',
            field=models.ForeignKey(blank=True, help_text='Peraturan penjaminan mutu yang berlaku saat siklus ini dilaksanakan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siklus_set', to='ami_core.regulasiacuan'),
        ),
    ]
