# Generated by Django 5.2.13 on 2026-09-08 11:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_core', '0007_fix_isi_rujukan_sn_dikti'),
        ('ami_user', '0002_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('domain_induk', models.CharField(blank=True, max_length=150, null=True)),
                ('keterangan', models.CharField(blank=True, help_text='Rujukan pasal.', max_length=200, null=True)),
                ('no_urut', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Master Standar',
                'verbose_name_plural': 'Master Standar',
                'db_table': 'master_standar',
                'ordering': ['no_urut'],
            },
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='butir_kritis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butir_created_set', to='ami_user.userami'),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='dasar_hukum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='dokumen_bukti_wajib',
            field=models.JSONField(blank=True, help_text='Daftar [{"nama": "...", "wajib": true}, ...].', null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='domain',
            field=models.CharField(blank=True, choices=[('PDD', 'Pendidikan'), ('PNL', 'Penelitian'), ('PKM', 'Pengabdian kepada Masyarakat'), ('NAK', 'Nonakademik')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='indikator_ketercapaian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='jenis_jawaban',
            field=models.CharField(blank=True, choices=[('JJ-1', 'Skala 0-4'), ('JJ-2', 'Ya / Tidak'), ('JJ-3', 'Numerik'), ('JJ-4', 'Persentase'), ('JJ-5', 'Uraian + Bukti')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='kaitan_akreditasi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='kelompok_standar',
            field=models.CharField(blank=True, choices=[('L', 'Luaran'), ('P', 'Proses'), ('M', 'Masukan'), ('T', 'Tata Kelola SPMI')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='lapis_audit',
            field=models.CharField(choices=[('kepatuhan', 'Kepatuhan SN Dikti'), ('pelampauan', 'Pelampauan (Unggul)')], default='kepatuhan', max_length=20),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='metode_verifikasi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='pernyataan_butir',
            field=models.TextField(blank=True, help_text='Pernyataan auditable (dapat dijawab terpenuhi/tidak).', null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='rubrik_skor',
            field=models.JSONField(blank=True, help_text='Daftar [{"skor": 0-4, "deskripsi": "..."}, ...].', null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='sasaran_auditee',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='status',
            field=models.CharField(choices=[('draf', 'Draf'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('diarsipkan', 'Diarsipkan')], default='aktif', max_length=20),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='sub_standar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='sumber_data',
            field=models.CharField(blank=True, choices=[('SD-1', 'PD Dikti'), ('SD-2', 'SIMAK / SIA UNISAN'), ('SD-3', 'Dokumen Prodi'), ('SD-4', 'Dokumen UPPS/Fakultas'), ('SD-5', 'Dokumen Universitas'), ('SD-6', 'Survei / Tracer Study')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='tahap_audit',
            field=models.CharField(blank=True, choices=[('TA-1', 'Desk Evaluasi (Audit Sistem)'), ('TA-2', 'Audit Lapangan (Audit Kepatuhan)'), ('TA-3', 'Keduanya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butir_updated_set', to='ami_user.userami'),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='versi',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='butirpenilaian',
            name='rujukan_sn_dikti',
            field=models.CharField(blank=True, help_text='Deprecated -- dipertahankan untuk kompatibilitas lama, gunakan dasar_hukum.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='butirpenilaian',
            name='master_standar',
            field=models.ForeignKey(blank=True, help_text='Pemetaan ke taksonomi Pasal 5 SN-Dikti (39/2025). Boleh kosong untuk butir lama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butir_set', to='ami_core.masterstandar'),
        ),
        migrations.CreateModel(
            name='RefEnumerasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.CharField(max_length=50)),
                ('kode', models.CharField(max_length=20)),
                ('nilai', models.CharField(max_length=200)),
                ('domain_induk', models.CharField(blank=True, max_length=150, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('no_urut', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Referensi Enumerasi',
                'verbose_name_plural': 'Referensi Enumerasi',
                'db_table': 'ref_enumerasi',
                'ordering': ['kelompok', 'no_urut'],
                'constraints': [models.UniqueConstraint(fields=('kelompok', 'kode'), name='uniq_ref_enumerasi_kelompok_kode')],
            },
        ),
    ]
