# Generated by Django 5.2.13 on 2026-09-07 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_core', '0002_seed_reference_data'),
        ('ami_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('tgl_rapat', models.DateField()),
                ('waktu_mulai', models.TimeField(blank=True, null=True)),
                ('waktu_selesai', models.TimeField(blank=True, null=True)),
                ('tempat', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('terjadwal', 'Terjadwal'), ('sedang_berlangsung', 'Sedang Berlangsung'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='terjadwal', max_length=20)),
                ('notulen_file', models.CharField(blank=True, max_length=500, null=True)),
                ('sk_keputusan_file', models.CharField(blank=True, max_length=500, null=True)),
                ('foto_dokumentasi', models.JSONField(blank=True, null=True)),
                ('jml_peserta', models.PositiveIntegerField(default=0)),
                ('jml_keputusan', models.PositiveIntegerField(default=0)),
                ('jml_action_item', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtm_notulis_set', to='ami_user.userami')),
                ('pemimpin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtm_pemimpin_set', to='ami_user.userami')),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtm_set', to='ami_core.siklus')),
            ],
            options={
                'verbose_name': 'RTM',
                'verbose_name_plural': 'RTM',
                'db_table': 'rtm',
                'ordering': ['-tgl_rapat'],
            },
        ),
        migrations.CreateModel(
            name='RtmAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut', models.PositiveIntegerField()),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('prioritas', models.CharField(blank=True, choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('kritis', 'Kritis')], max_length=20, null=True)),
                ('estimasi_anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sumber_anggaran', models.CharField(blank=True, max_length=200, null=True)),
                ('pic_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('is_voting_enabled', models.BooleanField(default=False)),
                ('voting_setuju', models.PositiveIntegerField(default=0)),
                ('voting_tidak', models.PositiveIntegerField(default=0)),
                ('voting_abstain', models.PositiveIntegerField(default=0)),
                ('keputusan', models.CharField(blank=True, choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('ditunda', 'Ditunda')], max_length=20, null=True)),
                ('keputusan_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtm_agenda_pic_set', to='ami_user.userami')),
                ('rtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_set', to='ami_rtm.rtm')),
            ],
            options={
                'verbose_name': 'Agenda RTM',
                'verbose_name_plural': 'Agenda RTM',
                'db_table': 'rtm_agenda',
                'ordering': ['rtm', 'no_urut'],
            },
        ),
        migrations.CreateModel(
            name='RtmNotulen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('tipe', models.CharField(choices=[('komentar', 'Komentar'), ('pertanyaan', 'Pertanyaan'), ('usulan', 'Usulan'), ('action_item', 'Action Item'), ('keputusan', 'Keputusan'), ('sistem', 'Sistem')], default='komentar', max_length=20)),
                ('is_action_item', models.BooleanField(default=False)),
                ('action_deadline', models.DateField(blank=True, null=True)),
                ('action_status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('waktu_kirim', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('action_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtm_action_pic_set', to='ami_user.userami')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_set', to='ami_rtm.rtmnotulen')),
                ('rtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notulen_set', to='ami_rtm.rtm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtm_notulen_set', to='ami_user.userami')),
            ],
            options={
                'verbose_name': 'Notulen RTM',
                'verbose_name_plural': 'Notulen RTM',
                'db_table': 'rtm_notulen',
                'ordering': ['rtm', 'waktu_kirim'],
            },
        ),
    ]
