# Generated by Django 5.2.13 on 2026-09-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_rtm', '0001_initial'),
        ('ami_user', '0002_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtmVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.CharField(choices=[('setuju', 'Setuju'), ('tidak', 'Tidak Setuju'), ('abstain', 'Abstain')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='ami_rtm.rtmagenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtm_vote_set', to='ami_user.userami')),
            ],
            options={
                'verbose_name': 'Vote RTM',
                'verbose_name_plural': 'Vote RTM',
                'db_table': 'rtm_vote',
                'constraints': [models.UniqueConstraint(fields=('agenda', 'user'), name='uniq_rtm_vote_agenda_user')],
            },
        ),
    ]
