# Generated by Django 5.2.13 on 2026-09-07 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ami_assessment', '0001_initial'),
        ('ami_core', '0002_seed_reference_data'),
        ('ami_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DePenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_dalam_tim', models.CharField(choices=[('ketua_tim', 'Ketua Tim'), ('auditor', 'Auditor'), ('pendamping', 'Pendamping')], default='auditor', max_length=20)),
                ('sk_no', models.CharField(max_length=100)),
                ('sk_tgl', models.DateField()),
                ('sk_file', models.CharField(blank=True, max_length=500, null=True)),
                ('tgl_mulai_de', models.DateField()),
                ('tenggat_de', models.DateField()),
                ('tgl_selesai_aktual', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ditugaskan', 'Ditugaskan'), ('dimulai', 'Dimulai'), ('on_progress', 'On Progress'), ('selesai_de', 'Selesai DE'), ('difinalisasi', 'Difinalisasi'), ('dibatalkan', 'Dibatalkan')], default='ditugaskan', max_length=30)),
                ('total_butir', models.PositiveIntegerField(default=0)),
                ('butir_dinilai', models.PositiveIntegerField(default=0)),
                ('butir_skor_1', models.PositiveIntegerField(default=0)),
                ('butir_skor_0', models.PositiveIntegerField(default=0)),
                ('konflik_kepentingan_signed', models.BooleanField(default=False)),
                ('konflik_kepentingan_signed_at', models.DateTimeField(blank=True, null=True)),
                ('catatan_lp3m', models.TextField(blank=True, null=True)),
                ('catatan_auditor', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='de_penugasan_set', to='ami_user.userami')),
                ('pengisian', models.ForeignKey(help_text='Auditee (self-assessment yang dinilai)', on_delete=django.db.models.deletion.PROTECT, related_name='de_penugasan_set', to='ami_assessment.pengisian')),
                ('siklus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='de_penugasan_set', to='ami_core.siklus')),
            ],
            options={
                'verbose_name': 'Penugasan DE',
                'verbose_name_plural': 'Penugasan DE',
                'db_table': 'de_penugasan',
                'ordering': ['-siklus', 'tenggat_de'],
            },
        ),
        migrations.CreateModel(
            name='DePenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 — Tidak Sesuai'), (1, '1 — Sesuai')], null=True)),
                ('klasifikasi', models.CharField(blank=True, choices=[('KTB', 'Ketidaksesuaian Berat'), ('KTS', 'Ketidaksesuaian Sedang'), ('OB', 'Observasi'), ('BP', 'Best Practice')], max_length=10, null=True)),
                ('plor_problem', models.TextField(blank=True, null=True, verbose_name='PLOR — Problem')),
                ('plor_location', models.CharField(blank=True, max_length=300, null=True, verbose_name='PLOR — Location')),
                ('plor_objective', models.CharField(blank=True, max_length=500, null=True, verbose_name='PLOR — Objective')),
                ('plor_reference', models.CharField(blank=True, max_length=500, null=True, verbose_name='PLOR — Reference')),
                ('catatan_auditor', models.TextField(blank=True, null=True)),
                ('rekomendasi_visitasi', models.TextField(blank=True, null=True)),
                ('dokumen_diperiksa', models.JSONField(blank=True, help_text='Array id DokumenBukti yang diperiksa', null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_finalisasi', models.BooleanField(default=False)),
                ('dinilai_pada', models.DateTimeField(blank=True, null=True)),
                ('difinalisasi_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='de_penilaian_set', to='ami_core.butirpenilaian')),
                ('jawaban', models.ForeignKey(blank=True, help_text='Link ke jawaban auditee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_penilaian_set', to='ami_assessment.jawabanbutir')),
                ('penugasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_set', to='ami_de.depenugasan')),
            ],
            options={
                'verbose_name': 'Penilaian DE',
                'verbose_name_plural': 'Penilaian DE',
                'db_table': 'de_penilaian',
            },
        ),
        migrations.CreateModel(
            name='DeDaftarTilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_tilik', models.TextField()),
                ('prioritas', models.CharField(blank=True, choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], max_length=10, null=True)),
                ('metode_verifikasi', models.CharField(blank=True, choices=[('wawancara', 'Wawancara'), ('observasi', 'Observasi'), ('review_dokumen', 'Review Dokumen'), ('fgd', 'FGD'), ('inspeksi_lapangan', 'Inspeksi Lapangan')], max_length=30, null=True)),
                ('sasaran_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('status_visitasi', models.CharField(choices=[('belum_diperiksa', 'Belum Diperiksa'), ('terkonfirmasi', 'Terkonfirmasi'), ('tidak_terkonfirmasi', 'Tidak Terkonfirmasi'), ('perlu_followup', 'Perlu Follow-up')], default='belum_diperiksa', max_length=20)),
                ('catatan_visitasi', models.TextField(blank=True, null=True)),
                ('diperiksa_pada', models.DateTimeField(blank=True, null=True)),
                ('no_urut', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_tilik_set', to='ami_core.butirpenilaian')),
                ('diperiksa_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tilik_diperiksa_set', to='ami_user.userami')),
                ('penilaian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daftar_tilik_set', to='ami_de.depenilaian')),
                ('penugasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tilik_set', to='ami_de.depenugasan')),
            ],
            options={
                'verbose_name': 'Daftar Tilik DE',
                'verbose_name_plural': 'Daftar Tilik DE',
                'db_table': 'de_daftar_tilik',
                'ordering': ['penugasan', 'no_urut'],
            },
        ),
        migrations.AddConstraint(
            model_name='depenugasan',
            constraint=models.UniqueConstraint(fields=('pengisian', 'auditor'), name='uniq_de_penugasan_pengisian_auditor'),
        ),
        migrations.AddConstraint(
            model_name='depenilaian',
            constraint=models.CheckConstraint(condition=models.Q(('skor__in', [0, 1]), ('skor__isnull', True), _connector='OR'), name='chk_de_penilaian_skor_binary'),
        ),
        migrations.AddConstraint(
            model_name='depenilaian',
            constraint=models.UniqueConstraint(fields=('penugasan', 'butir'), name='uniq_de_penilaian_penugasan_butir'),
        ),
    ]
