# Generated by Django 5.2.13 on 2026-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_assessment', '0001_initial'),
        ('ami_core', '0010_lengkapi_58_butir_riil_taksonomi_baru'),
        ('ami_de', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depenilaian',
            name='chk_de_penilaian_skor_binary',
        ),
        migrations.AlterField(
            model_name='depenilaian',
            name='klasifikasi',
            field=models.CharField(blank=True, choices=[('SESUAI', 'Sesuai (Conformity)'), ('OB', 'Observasi (OB)'), ('KTS_MINOR', 'Ketidaksesuaian Minor (KTS Minor)'), ('KTS_MAYOR', 'Ketidaksesuaian Mayor (KTS Mayor)'), ('KTB', 'Ketidaksesuaian Berat (legacy)'), ('KTS', 'Ketidaksesuaian Sedang (legacy)'), ('BP', 'Best Practice (legacy)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='depenilaian',
            name='skor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 — Tidak Ada'), (1, '1 — Kurang'), (2, '2 — Cukup'), (3, '3 — Baik / Terpenuhi'), (4, '4 — Sangat Baik / Melampaui')], null=True),
        ),
        migrations.AddConstraint(
            model_name='depenilaian',
            constraint=models.CheckConstraint(condition=models.Q(('skor__in', [0, 1, 2, 3, 4]), ('skor__isnull', True), _connector='OR'), name='chk_de_penilaian_skor_0_4'),
        ),
    ]
