# Generated by Django 5.2.13 on 2026-09-07 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('nama_singkat', models.CharField(max_length=20)),
                ('dekan_user_id', models.IntegerField(blank=True, null=True)),
                ('upm_user_id', models.IntegerField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('source_schema', models.CharField(default='akademik', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fakultas',
                'db_table': 'fakultas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('kode_pddikti', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('nama_inggris', models.CharField(blank=True, max_length=200, null=True)),
                ('strata', models.CharField(choices=[('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('Profesi', 'Profesi')], max_length=10)),
                ('kaprodi_user_id', models.IntegerField(blank=True, null=True)),
                ('sekprodi_user_id', models.IntegerField(blank=True, null=True)),
                ('sk_pendirian_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_pendirian_tgl', models.DateField(blank=True, null=True)),
                ('sk_pendirian_file', models.CharField(blank=True, max_length=500, null=True)),
                ('akreditasi_lembaga', models.CharField(blank=True, choices=[('BAN-PT', 'BAN-PT'), ('LAM-PTKes', 'LAM-PTKes'), ('LAMSAMA', 'LAMSAMA'), ('LAMINFOKOM', 'LAMINFOKOM'), ('LAM-Teknik', 'LAM-Teknik'), ('Belum', 'Belum')], max_length=20, null=True)),
                ('akreditasi_peringkat', models.CharField(blank=True, choices=[('Unggul', 'Unggul'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik'), ('Terakreditasi', 'Terakreditasi'), ('Belum', 'Belum')], max_length=20, null=True)),
                ('akreditasi_no_sk', models.CharField(blank=True, max_length=100, null=True)),
                ('akreditasi_tgl_sk', models.DateField(blank=True, null=True)),
                ('akreditasi_berlaku_sd', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('source_schema', models.CharField(default='akademik', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodi_set', to='ami_master.fakultas')),
            ],
            options={
                'verbose_name_plural': 'Prodi',
                'db_table': 'prodi',
                'ordering': ['nama'],
            },
        ),
    ]
