# Generated by Django 5.2.13 on 2026-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultas',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fakultas',
            name='source_schema',
            field=models.CharField(default='master', max_length=20),
        ),
        migrations.AlterField(
            model_name='prodi',
            name='akreditasi_peringkat',
            field=models.CharField(blank=True, choices=[('Unggul', 'Unggul'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik'), ('Terakreditasi', 'Terakreditasi'), ('A', 'A (skema lama)'), ('B', 'B (skema lama)'), ('C', 'C (skema lama)'), ('Belum', 'Belum')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prodi',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prodi',
            name='source_schema',
            field=models.CharField(default='master', max_length=20),
        ),
    ]
