# Generated by Django 5.2.13 on 2026-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_master', '0003_seed_fakultas_prodi_from_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodi',
            name='tanggal_mulai_beroperasi',
            field=models.DateField(blank=True, help_text='Dasar hitung tenggat wajib ajukan akreditasi 2 tahun (Permendiktisaintek 39/2025 Pasal 77 ayat 1).', null=True),
        ),
    ]
