# Generated by Django 5.2.13 on 2026-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_master', '0004_prodi_tanggal_mulai_beroperasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodi',
            name='status_akreditasi',
            field=models.CharField(blank=True, choices=[('tidak_terakreditasi', 'Tidak Terakreditasi'), ('terakreditasi_pertama', 'Terakreditasi Pertama'), ('terakreditasi', 'Terakreditasi'), ('terakreditasi_unggul', 'Terakreditasi Unggul'), ('terakreditasi_sementara', 'Terakreditasi Sementara (nomenklatur lama)')], help_text='Syarat kelayakan meluluskan mahasiswa/menerbitkan ijazah (Pasal 70 ayat 4).', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodi',
            name='status_asal',
            field=models.CharField(blank=True, help_text='Jejak audit: nilai akreditasi_peringkat sebelum status_akreditasi diisi eksplisit pertama kali.', max_length=100, null=True),
        ),
    ]
