# Generated by Django 5.2.13 on 2026-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami_master', '0006_petakan_status_akreditasi_16_prodi_riil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodi',
            name='akreditasi_lembaga',
            field=models.CharField(blank=True, choices=[('BAN-PT', 'BAN-PT'), ('LAM-PTKes', 'LAM-PTKes'), ('LAM-Teknik', 'LAM-Teknik'), ('LAMDIK', 'LAMDIK (Kependidikan)'), ('LAMINFOKOM', 'LAMINFOKOM'), ('LAMSAMA', 'LAMSAMA'), ('LAMEMBA', 'LAMEMBA (Ekonomi, Manajemen, Bisnis, Akuntansi)'), ('LAMSPAK', 'LAMSPAK (Sosial, Politik, Administrasi, Komunikasi)'), ('Belum', 'Belum')], max_length=20, null=True),
        ),
    ]
